LIBNAME LIBRARY "E:\6300\project";
OPTIONS PAGENO=1;                                                            
TITLE1 'STAT 6300 PROJECT JM&SZ';                                                         
TITLE2 'UNBALANCE MULTIVARIATE TWO-WAY MANOVA'; 
DATA ONE ; SET LIBRARY.INTEREST;
DATA AA; SET ONE;
KEEP gender age socdom sociabty stress worry impulsve thrillsk;

DATA AA; SET AA;
 IF age<30  THEN GRP=1;
 IF 30<age<40 or age=30 THEN GRP=2;
 IF 40<age<50 or age=40 THEN GRP=3;
ELSE IF age>50 or age=50 THEN GRP=4;
PROC PRINT;
RUN;
* (a);
* MEAN OF 6 VARIABLES BY GENDER;
PROC SORT DATA=AA; BY gender;                                                            
PROC MEANS DATA=AA; BY gender;                                                           
 VAR socdom sociabty stress worry impulsve thrillsk;                                                             
RUN;
* MEAN OF 6 VARIABLES BY GROUP;
PROC SORT DATA=AA; BY GRP;                                                             
PROC MEANS DATA=AA; BY GRP;                                                            
 VAR socdom sociabty stress worry impulsve thrillsk;                                                             
RUN;
* MEAN OF 6 VARIABLES BY GENDER AND GROUP;
PROC SORT DATA=AA; BY gender GRP;                                                       
PROC MEANS DATA=AA; BY gender GRP;                                                      
 VAR socdom sociabty stress worry impulsve thrillsk;                                                             
RUN;
* UNBALANCE MULTIVARIATE TWO-WAY MANOVA, FIRST WITH INTERACTION TERM;
PROC GLM DATA=AA; CLASS gender GRP;                                                     
  MODEL socdom sociabty stress worry impulsve thrillsk = gender GRP gender*GRP;                                  
  MANOVA H=_ALL_/PRINTH PRINTE SHORT;                                           
  MEANS gender|GRP/TUKEY LINES;                                                 
  LSMEANS gender*GRP/PDIFF;                                                     
  LSMEANS gender*GRP/PDIFF=ALL ADJUST=TUKEY;                                                     
RUN; 
*exact p-value for the MANOVA tests;
PROC GLM DATA=AA; CLASS gender GRP ;                                                     
  MODEL socdom sociabty stress worry impulsve thrillsk= gender GRP gender*GRP;                                  
  MANOVA H=_ALL_/MSTAT=EXACT;                                           
  ODS SELECT MULTSTAT;
RUN;
* UNBALANCE MULTIVARIATE TWO-WAY MANOVA, INTERACTION TERM IS NOT SIGNIFICANT;
PROC GLM DATA=AA; CLASS gender GRP;                                                     
  MODEL socdom sociabty stress worry impulsve thrillsk = gender GRP;                                             
  MANOVA H=_ALL_/PRINTH PRINTE SHORT;                                           
  MEANS gender GRP;                                                 
  LSMEANS gender GRP/PDIFF; 
RUN; 
*exact p-value for the MANOVA tests;
PROC GLM DATA=AA; CLASS gender GRP ;                                                     
  MODEL socdom sociabty stress worry impulsve thrillsk= gender GRP;                                  
  MANOVA H=_ALL_/MSTAT=EXACT;                                           
  ODS SELECT MULTSTAT;
RUN;
* OPTIONAL CHOICE, IGNORE GENDER. UNBALANCE MULTIVARIATE TWO-WAY MANOVA, ONLY GROUP IS SIGNIFICANT;
PROC GLM DATA=AA; CLASS GRP;                                                     
  MODEL socdom sociabty stress worry impulsve thrillsk =GRP;                                             
  MANOVA H=_ALL_/PRINTH PRINTE SHORT;                                           
  MEANS GRP/TUKEY;;
RUN; 
*exact p-value for the MANOVA tests;                                                                    
PROC GLM DATA=AA; CLASS GRP;                                                          
  MODEL socdom sociabty stress worry impulsve thrillsk =GRP;                                                  
  MANOVA H=_ALL_/MSTAT=EXACT;                                           
  ODS SELECT MULTSTAT; 
RUN; 
* MODEL USING TREATMENT COMBINATION;
DATA A; SET AA;                                                                  
 IF gender=1 AND GRP=1 THEN TRT=1;                                              
 ELSE IF gender=1 AND GRP=2 THEN TRT=2;                                         
 ELSE IF gender=1 AND GRP=3 THEN TRT=3;                                         
 ELSE IF gender=1 AND GRP=4 THEN TRT=4;                                         
 ELSE IF gender=2 AND GRP=1 THEN TRT=5;                                         
 ELSE IF gender=2 AND GRP=2 THEN TRT=6;                                         
 ELSE IF gender=2 AND GRP=3 THEN TRT=7;                                         
 ELSE IF gender=2 AND GRP=4 THEN TRT=8;  
RUN;
PROC PRINT DATA=A;
* RUN TUKEY ON 8 TREATMENT COMBINATION;
PROC GLM DATA=A; CLASS TRT;                                                            
  MODEL socdom sociabty stress worry impulsve thrillsk= TRT;                                              
  MANOVA H=_ALL_/PRINTH SHORT;                                                  
  MEANS TRT/TUKEY;
  LSMEANS TRT/PDIFF ADJUST=TUKEY;
RUN;
* EXACT P-VALUE;
PROC GLM DATA=A; CLASS TRT;                                                            
  MODEL socdom sociabty stress worry impulsve thrillsk = TRT;                                              
  MANOVA H=_ALL_/MSTAT=EXACT;
  ODS SELECT MULTSTAT;
 RUN;
PROC FACTOR DATA=AA R=V N=2 out=BB;                                                          
 VAR socdom sociabty stress worry impulsve thrillsk;                                                                    
RUN; 
proc print data=BB;
run;
proc corr data=BB;
var factor1-factor2;
run;
proc means data=BB; class GPR;
var factor1-factor2;
run;
proc glm data=BB; class GPR;
model factor1-factor2=GPR;
manova H=GRP;
means GRP/tukey;
run;

PROC corr data=AA nomiss alpha nosimple nocorr;
var stress worry impulsve thrillsk;
run;



